"""
Linear Issue Templates
Ported from SpineHUB.

Provides parametrized templates for automated ticket creation.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Dict, List, Optional


@dataclass
class IssueTemplate:
    """Issue template for automated ticket creation."""
    id: str
    name: str
    description: str
    title_pattern: str
    body_template: str
    labels: List[str] = field(default_factory=list)
    default_assignee: Optional[str] = None
    estimate_points: Optional[int] = None
    priority: Optional[int] = None  # 0-4 (0=no priority, 1=urgent, 4=low)


@dataclass
class MatrixRow:
    """Project matrix row for automation."""
    project_name: str
    project_id: str
    current_state: str
    progress_pct: int
    issue_count: int
    lead: str
    latest_update: str
    health: str  # "onTrack", "atRisk", "offTrack"
    target_date: str
    url: str
    # Optional automation fields
    create_weekly_update: bool = False
    create_milestone_ticket: bool = False
    ticket_title: Optional[str] = None
    ticket_description: Optional[str] = None
    ticket_labels: List[str] = field(default_factory=list)
    ticket_assignee: Optional[str] = None


def create_template(
    id: str,
    name: str,
    description: str,
    title_pattern: str,
    body_template: str,
    labels: List[str] = None,
    priority: int = None,
) -> IssueTemplate:
    """Factory function to create an issue template."""
    return IssueTemplate(
        id=id,
        name=name,
        description=description,
        title_pattern=title_pattern,
        body_template=body_template,
        labels=labels or [],
        priority=priority,
    )


def apply_template_variables(text: str, variables: dict) -> str:
    """
    Replace template variables with actual values.

    Supported variables:
    - {{project_name}} - Project name
    - {{date}} - Today's date (YYYY-MM-DD)
    - {{state}} - Current state
    - {{progress}} - Progress percentage
    - {{project_url}} - Project URL
    - {{current_state}} - Current state (alias)
    - {{progress_pct}} - Progress percentage (alias)
    - {{issue_count}} - Number of issues
    - {{lead}} - Project lead
    - {{health}} - Health status
    - {{target_date}} - Target date
    - {{latest_update}} - Latest update text
    """
    replacements = {
        "{{project_name}}": variables.get("project_name", ""),
        "{{date}}": datetime.now().strftime("%Y-%m-%d"),
        "{{state}}": variables.get("current_state", ""),
        "{{progress}}": str(variables.get("progress_pct", 0)),
        "{{project_url}}": variables.get("url", ""),
        "{{current_state}}": variables.get("current_state", ""),
        "{{progress_pct}}": str(variables.get("progress_pct", 0)),
        "{{issue_count}}": str(variables.get("issue_count", 0)),
        "{{lead}}": variables.get("lead", "Not assigned"),
        "{{health}}": variables.get("health", ""),
        "{{target_date}}": variables.get("target_date", "Not set"),
        "{{latest_update}}": variables.get("latest_update", ""),
    }

    result = text
    for var, value in replacements.items():
        result = result.replace(var, str(value))

    return result


# Default templates ported from LINEAR_AUTO
DEFAULT_TEMPLATES: Dict[str, IssueTemplate] = {
    "weekly_update": IssueTemplate(
        id="weekly_update",
        name="Weekly Status Update",
        description="Create weekly status update ticket for project",
        title_pattern="[{{project_name}}] Weekly Status Update - {{date}}",
        body_template="""## Project Status Update

**Project:** {{project_name}}
**Current State:** {{current_state}}
**Progress:** {{progress_pct}}%
**Health:** {{health}}

### Recent Activity
{{latest_update}}

### Action Items
- [ ] Review current blockers
- [ ] Update stakeholders
- [ ] Plan next week's priorities

---
*Auto-generated by SpineHUB*
[View Project]({{project_url}})""",
        labels=["status-update", "weekly"],
        priority=3,
    ),

    "at_risk_alert": IssueTemplate(
        id="at_risk_alert",
        name="At Risk Alert",
        description="Create alert ticket for at-risk projects",
        title_pattern="[ALERT] {{project_name}} - At Risk",
        body_template="""## At Risk Alert

**Project:** {{project_name}}
**Current State:** {{current_state}}
**Progress:** {{progress_pct}}%
**Lead:** {{lead}}
**Target Date:** {{target_date}}

### Latest Update
{{latest_update}}

### Required Actions
- [ ] Identify root cause of risk
- [ ] Create mitigation plan
- [ ] Escalate if needed
- [ ] Schedule review meeting

---
*Auto-generated by SpineHUB*
[View Project]({{project_url}})""",
        labels=["at-risk", "urgent"],
        priority=1,
    ),

    "stale_project": IssueTemplate(
        id="stale_project",
        name="Stale Project Review",
        description="Create review ticket for stale projects",
        title_pattern="[Review Needed] {{project_name}} - No Recent Updates",
        body_template="""## Stale Project Review

**Project:** {{project_name}}
**State:** {{current_state}}
**Progress:** {{progress_pct}}%
**Lead:** {{lead}}

This project has not received updates recently.

### Questions to Address
- [ ] Is this project still active?
- [ ] Are there blockers preventing progress?
- [ ] Should the project be paused or canceled?
- [ ] Does the lead need support?

---
*Auto-generated by SpineHUB*
[View Project]({{project_url}})""",
        labels=["review", "stale"],
        priority=2,
    ),

    "milestone_reached": IssueTemplate(
        id="milestone_reached",
        name="Milestone Celebration",
        description="Create celebration ticket for milestone achievements",
        title_pattern="[Milestone] {{project_name}} - {{progress}}% Complete!",
        body_template="""## Milestone Reached!

**Project:** {{project_name}}
**Progress:** {{progress_pct}}%
**Lead:** {{lead}}

Congratulations on reaching this milestone!

### Achievements
- Progress milestone reached
- {{issue_count}} issues tracked

### Next Steps
- [ ] Celebrate with the team
- [ ] Document lessons learned
- [ ] Plan next phase

---
*Auto-generated by SpineHUB*
[View Project]({{project_url}})""",
        labels=["milestone", "celebration"],
        priority=4,
    ),

    "daily_status": IssueTemplate(
        id="daily_status",
        name="Daily Status Update",
        description="Create daily status update for TSA agenda",
        title_pattern="[Daily Agenda] {{project_name}} - {{date}}",
        body_template="""## Daily Status Update

**Project:** {{project_name}}
**Current Focus:** {{latest_update}}

### Tasks
- DO: [pending task] - ETA: [date]
- DONE: [completed task]
- BLOCKED: [blocked task] (if any)

### Status
- **Progress:** {{progress_pct}}%
- **Health:** {{health}}
- **Lead:** {{lead}}

**ESCALATION:** None
**BLOCKERS:** None

---
*Auto-generated by SpineHUB*
[View Project]({{project_url}})""",
        labels=["tsa-routine", "daily"],
        priority=3,
    ),

    "blocker_alert": IssueTemplate(
        id="blocker_alert",
        name="Blocker Alert",
        description="Create alert for blocked projects",
        title_pattern="[BLOCKED] {{project_name}} - Action Required",
        body_template="""## Project Blocker Alert

**Project:** {{project_name}}
**Lead:** {{lead}}
**Progress:** {{progress_pct}}%

### Blocker Details
{{latest_update}}

### Resolution Steps
- [ ] Identify blocker owner
- [ ] Determine resolution path
- [ ] Set ETA for resolution
- [ ] Escalate if external dependency

### Impact
- Target Date: {{target_date}}
- Health: {{health}}

---
*Auto-generated by SpineHUB*
[View Project]({{project_url}})""",
        labels=["blocked", "action-required"],
        priority=1,
    ),
}


def get_template(template_id: str) -> Optional[IssueTemplate]:
    """Get a template by ID."""
    return DEFAULT_TEMPLATES.get(template_id)


def list_templates() -> List[IssueTemplate]:
    """List all available templates."""
    return list(DEFAULT_TEMPLATES.values())
