/**
 * Linear Templates - TypeScript wrapper for issue templates
 *
 * Provides access to 6 pre-defined issue templates:
 * - weekly_update: Weekly status update
 * - at_risk_alert: At-risk project alert
 * - stale_project: Stale project notification
 * - milestone_reached: Milestone completion
 * - daily_status: Daily status update
 * - blocker_alert: Blocker notification
 */

import { getPythonBridge, BridgeResponse } from '../bridge';
import { IssueTemplate, TemplateListResult, ApplyTemplateResult } from '../types';

export type TemplateId =
  | 'weekly_update'
  | 'at_risk_alert'
  | 'stale_project'
  | 'milestone_reached'
  | 'daily_status'
  | 'blocker_alert';

export interface TemplateVariables {
  [key: string]: string | number | boolean;
}

/**
 * LinearTemplates - Issue template management
 */
export class LinearTemplates {
  /**
   * List all available templates
   */
  async listTemplates(): Promise<IssueTemplate[]> {
    const bridge = getPythonBridge();
    const response = await bridge.call<TemplateListResult>('linear.list_templates', {});

    if (!response.success) {
      console.error('Failed to list templates:', response.error);
      return [];
    }

    return response.data?.templates || [];
  }

  /**
   * Get a specific template by ID
   */
  async getTemplate(templateId: TemplateId): Promise<IssueTemplate | null> {
    const bridge = getPythonBridge();
    const response = await bridge.call<IssueTemplate>('linear.get_template', {
      template_id: templateId,
    });

    if (!response.success) {
      return null;
    }

    return response.data || null;
  }

  /**
   * Apply variables to a template
   */
  async applyTemplate(templateId: TemplateId, variables: TemplateVariables): Promise<ApplyTemplateResult | null> {
    const bridge = getPythonBridge();
    const response = await bridge.call<ApplyTemplateResult>('linear.apply_template', {
      template_id: templateId,
      variables,
    });

    if (!response.success) {
      console.error('Failed to apply template:', response.error);
      return null;
    }

    return response.data || null;
  }

  /**
   * Get template variable placeholders
   */
  async getTemplateVariables(templateId: TemplateId): Promise<string[]> {
    const template = await this.getTemplate(templateId);
    if (!template) return [];

    return template.variables || [];
  }

  /**
   * Print available templates
   */
  async printTemplates(): Promise<void> {
    const templates = await this.listTemplates();

    console.log('\n' + '=' .repeat(60));
    console.log('         LINEAR ISSUE TEMPLATES');
    console.log('=' .repeat(60) + '\n');

    for (const template of templates) {
      console.log(`[${template.id}] ${template.name}`);
      console.log(`  Title: ${template.title_pattern}`);
      console.log(`  Labels: ${template.labels.join(', ')}`);
      console.log(`  Variables: ${template.variables.join(', ')}`);
      console.log();
    }

    console.log('=' .repeat(60) + '\n');
  }
}

/**
 * Quick function to list templates
 */
export async function listLinearTemplates(): Promise<IssueTemplate[]> {
  const templates = new LinearTemplates();
  return templates.listTemplates();
}

/**
 * Quick function to get a template
 */
export async function getLinearTemplate(templateId: TemplateId): Promise<IssueTemplate | null> {
  const templates = new LinearTemplates();
  return templates.getTemplate(templateId);
}

/**
 * Quick function to apply template
 */
export async function applyLinearTemplate(
  templateId: TemplateId,
  variables: TemplateVariables
): Promise<ApplyTemplateResult | null> {
  const templates = new LinearTemplates();
  return templates.applyTemplate(templateId, variables);
}

// ============================================
// Built-in Template Definitions (fallback)
// ============================================

export const BUILTIN_TEMPLATES: Record<TemplateId, Omit<IssueTemplate, 'variables'>> = {
  weekly_update: {
    id: 'weekly_update',
    name: 'Weekly Status Update',
    title_pattern: '[Weekly Update] {owner_name} - {week_number}',
    body_template: `## Weekly Status Update

**Period:** {start_date} - {end_date}
**Owner:** {owner_name}

### Summary
{summary}

### Key Accomplishments
{accomplishments}

### Next Week Focus
{next_focus}

---
*Generated by TSA_CORTEX*`,
    labels: ['worklog', 'weekly'],
  },
  at_risk_alert: {
    id: 'at_risk_alert',
    name: 'At-Risk Project Alert',
    title_pattern: '[AT RISK] {project_name} - {risk_level}',
    body_template: `## At-Risk Alert

**Project:** {project_name}
**Risk Level:** {risk_level}
**Flagged By:** {owner_name}

### Risk Description
{risk_description}

### Impact
{impact}

### Mitigation Plan
{mitigation}

### Required Actions
{actions}

---
*Generated by TSA_CORTEX*`,
    labels: ['at-risk', 'alert', 'urgent'],
  },
  stale_project: {
    id: 'stale_project',
    name: 'Stale Project Notification',
    title_pattern: '[STALE] {project_name} - No activity for {days} days',
    body_template: `## Stale Project Alert

**Project:** {project_name}
**Days Since Activity:** {days}
**Last Activity:** {last_activity}

### Recommendation
{recommendation}

---
*Generated by TSA_CORTEX*`,
    labels: ['stale', 'needs-attention'],
  },
  milestone_reached: {
    id: 'milestone_reached',
    name: 'Milestone Completion',
    title_pattern: '[MILESTONE] {project_name} - {milestone_name}',
    body_template: `## Milestone Reached

**Project:** {project_name}
**Milestone:** {milestone_name}
**Completed:** {completion_date}

### Achievement
{achievement}

### Next Milestone
{next_milestone}

---
*Generated by TSA_CORTEX*`,
    labels: ['milestone', 'celebration'],
  },
  daily_status: {
    id: 'daily_status',
    name: 'Daily Status',
    title_pattern: '[Daily] {owner_name} - {date}',
    body_template: `## Daily Status

**Date:** {date}
**Owner:** {owner_name}

### Today
{today}

### Blockers
{blockers}

### Tomorrow
{tomorrow}

---
*Generated by TSA_CORTEX*`,
    labels: ['daily', 'status'],
  },
  blocker_alert: {
    id: 'blocker_alert',
    name: 'Blocker Alert',
    title_pattern: '[BLOCKER] {blocker_title}',
    body_template: `## Blocker Alert

**Title:** {blocker_title}
**Severity:** {severity}
**Reported By:** {owner_name}

### Description
{description}

### Impact
{impact}

### Help Needed
{help_needed}

---
*Generated by TSA_CORTEX*`,
    labels: ['blocker', 'urgent', 'help-wanted'],
  },
};
